# Generated by Django 4.1.1 on 2023-05-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0005_borrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date_added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='date_added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='date_added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='date_added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
