# Generated by Django 4.1.1 on 2023-05-19 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0006_alter_books_date_added_alter_borrow_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='middle_name',
        ),
    ]
